import { Github } from "lucide-react";
import { SelectRepositoryButton } from "@/components/repository/select-repository-button";
import { requireUser } from "@/lib/auth/session";
import { getGitHubRepositoriesForCurrentUser } from "@/lib/github/repositories";
import { SiteNavigation } from "@/components/site-navigation";
import { Badge } from "@/components/ui/badge";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
export default async function RepositoriesPage() { const user = await requireUser(); const result = await getGitHubRepositoriesForCurrentUser(); return <main className="sentinel-page"><SiteNavigation /><section className="mx-auto max-w-7xl px-6 py-14 lg:px-8 lg:py-20"><p className="eyebrow">REPOSITORIES / INDEX</p><div className="mt-4 border-b border-[#171817] pb-9"><h1 className="editorial-title text-4xl sm:text-6xl">Your code, under watch.</h1><p className="mt-5 max-w-2xl text-[#696b66]">Repositories available through the GitHub account connected to Sentinel.</p></div>{"error" in result ? <RepositoryError message={result.error} /> : result.repositories.length === 0 ? <EmptyRepositories userName={user.username ?? user.email ?? "your GitHub account"} /> : <div className="mt-10 border-t border-[#d5d6ce]">{result.repositories.map((repository, index) => <article key={repository.id} className="grid gap-5 border-b border-[#d5d6ce] py-6 lg:grid-cols-[4rem_1fr_auto] lg:items-center"><span className="font-mono text-xs text-[#696b66]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-medium tracking-[-.04em]">{repository.name}</h2><Badge variant={repository.private ? "warning" : "success"}>{repository.private ? "Private" : "Public"}</Badge></div><p className="mt-2 text-sm text-[#696b66]">{repository.owner.login} · {repository.language ?? "Language not specified"} · {repository.default_branch}</p><p className="mt-1 font-mono text-[10px] text-[#8a8d86]">UPDATED {formatUpdatedAt(repository.updated_at)}</p></div><SelectRepositoryButton owner={repository.owner.login} repositoryName={repository.name} /></article>)}</div>}</section></main>; }
function RepositoryError({ message }: { message: string }) { return <Card className="mt-10"><CardHeader><div className="grid h-10 w-10 place-items-center bg-[#d8ff42] text-[#171817]"><Github className="h-5 w-5" /></div><CardTitle className="mt-4">We couldn’t load your repositories</CardTitle><CardDescription>{message}</CardDescription></CardHeader></Card>; }
function EmptyRepositories({ userName }: { userName: string }) { return <Card className="mt-10"><CardHeader><div className="grid h-10 w-10 place-items-center bg-[#d8ff42] text-[#171817]"><Github className="h-5 w-5" /></div><CardTitle className="mt-4">No repositories found</CardTitle><CardDescription>GitHub did not return any repositories for {userName}.</CardDescription></CardHeader></Card>; }
function formatUpdatedAt(value: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date); }
